global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter 监控
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # 应用服务监控（假设您的应用在 8080 端口暴露指标）
  - job_name: 'asura-app'
    static_configs:
      - targets: ['app:8080']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  # Docker 容器监控（可选）
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']